server:
  port: ${PORT:${SERVER_PORT:80}}

info:
  id: ${spring.application.name}

debug: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:{server.port}/eureka/

---
spring:
  profiles: cloud
eureka:
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}

