spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
      
eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-server.credentials.uri:http://127.0.0.1:8761}/eureka/

---

spring:
  profiles: default
  jpa:
    database: HSQL

---

spring:
  profiles: pcf
  jpa:
    database: MYSQL

---

spring:
  profiles: pws
  jpa:
    database: POSTGRESQL
