server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-server.credentials.uri:http://127.0.0.1:8761}/eureka/

fortunes:
  ribbon:
    ServerListRefreshInterval: 5000

---

spring:
  profiles: pact

ribbon:
  eureka:
    enabled: false

hystrix:
  command:
    randomFortune:
      execution.isolation.thread.timeoutInMilliseconds: 2000

fortunes:
  ribbon:
    listOfServers: localhost:8080
