spring:
  jpa:
    hibernate:
      ddl-auto: create-drop

message: Hello Karlsruhe
---

spring:
  profiles: default
  jpa:
    database: HSQL

---

spring:
  profiles: pcf
  jpa:
    database: MYSQL

---

spring:
  profiles: cloud
  jpa:
    database: POSTGRESQL
